apiVersion: beta/v1
kind: Deployment
metadata:
  labels:
    app: mycontainer
  name: mycontainer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mycontainer
  template:
    metadata:
      labels:
        app: mycontainer
    spec:
      containers:
      - image: 8184848757/mycontainer:latest
        name: mycontainer
       
