apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycontainer
  labels:
    app: mycontainer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mycontainer
  template:
    metadata:
      labels:
        app: mycontainer
    spec:
      containers:
        - name: mycontainer
          image: http://07.20.47.69:8081/repository/docker-private/v2/mysecond/manifests/latest:latest
          imagePullSecrets:
            - name: evoke
          imagePullPolicy: Always
          ports:
          - name: mycontainer
            containerPort: 8086
            protocol: TCP
       #imagePullSecrets:
      - name: evoke
