apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycontainer
spec:
  containers:
    - name: mycontainer
      image: http://107.20.47.69:8081/repository/docker-private/
      imagePullPolicy: Always
      ports:
      - name: mycontainer
        containerPort: 8086
        protocol: TCP
  imagePullSecrets:
    - name: evoke
