apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycontainer
  labels:
    app: mycontainer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mycontainer
  template:
    metadata:
      labels:
        app: mycontainer
    spec:
      containers:
      - name: mycontainer
        image: http://34.229.84.181:8085/repository/docker-private/v2/mysecond/manifests/latest:latest
        imagePullPolicy: Always
      imagePullSecrets:
      - name: evoke
       