apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycontainer
  labels:
    app: mycontainer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mycontainer
  template:
    metadata:
      labels:
        app: mycontainer
    spec:
      containers:
        - name: mycontainer
          image: mysecond:latest
          imagePullPolicy: Always
          ports:
            - name: mycontainer
              containerPort: 8086
              protocol: TCP
      imagePullSecrets:
      - name: evoke
       
