apiVersion: v1
kind: Service
metadata:
  name: mycontainer
spec:
  selector:
    matchLabels:
      app: mycontainer
  ports:
    - protocal: TCP
      targetPort: 8086
      containerPort: 8086
