apiVersion: v1
kind: Service
metadata:
    name: mycontainer
    labels:
      app: mycontainer
spec:
  selector:
    app: mycontainer
  type: NodePort
  ports:
  - nodePort: 31000
    port: 8086
    targetPort: 8086
