apiVersion: v1
kind: Service
metadata:
    name: mycontainer
    labels:
      app: mycontainer
spec:
  selector:
    app: mycontainer
  type: NodePort
  ports:
  - nodePort: 32000
    port: 80
    targetPort: 80
